package org.zalando.nakadi.domain;

public enum CursorError {
    PARTITION_NOT_FOUND,
    UNAVAILABLE_AS_OFFSET_IN_FUTURE,
    UNAVAILABLE_AS_OFFSET_EXPIRED,
    UNAVAILABLE_AS_TIMELINE_DELETED,
    INVALID_FORMAT,
    NULL_PARTITION,
    NULL_OFFSET,
    FORBIDDEN,
    INVALID_OFFSET
}
