version: "2017-09-20"
pipeline:
  - id: test-build-push
    type: script
    vm_config:
      type: linux
      size: extra_large
      image: cdp-runtime/jdk11
    env:
      # Ensure that gradle will not be running after we are done using it,
      # so that we can clean up volatile gradle files in the cache:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    commands:
      - desc: Checkstyle
        cmd: |
          ./gradlew checkstyle --stacktrace

      - desc: Test
        cmd: |
          cdp-wrap-cmd "./gradlew test --stacktrace" "
            for dir in api-consumption api-cursors api-metastore api-misc api-publishing app core-common core-services plugins/authz; do
              rm -rf \${dir}/build/test-results/test/binary
              test_name=\$(echo \$dir | sed 's/\//-/g')
              cdp-upload-test-results --name \$test_name -t junit \${dir}/build/test-results/test
            done
            "
      - desc: Acceptance Test
        cmd: |
          apt-get install -y docker-compose-plugin
          cdp-wrap-cmd "./gradlew  fullAcceptanceTest --stacktrace" "rm -rf acceptance-test/build/test-results/acceptanceTest/binary;
            cdp-upload-test-results --name acceptance-test -t junit acceptance-test/build/test-results/acceptanceTest;"
      - desc: Build and push
        cmd: |
          # clean-build actually happens indirectly as part of running
          # acceptance-tests, so we can speed the build up by skipping it here
          #
          # ./nakadi.sh clean-build

          # https://docs.gradle.org/current/userguide/dependency_resolution.html#sub:cache_copy
          rm -f ~/.gradle/caches/modules-2/{*.lock,gc.properties}

          if [ -n "$CDP_PULL_REQUEST_NUMBER" ]; then
            MULTI_ARCH_IMAGE="container-registry-test.zalando.net/aruha/nakadi-base-pr:${CDP_BUILD_VERSION}"
          else
            MULTI_ARCH_IMAGE="container-registry-test.zalando.net/aruha/nakadi-base:${CDP_BUILD_VERSION}"
          fi

          ./nakadi.sh create-buildx /etc/cdp-buildkitd.toml
          ./nakadi.sh build-buildx ${MULTI_ARCH_IMAGE}

          cdp-promote-image ${MULTI_ARCH_IMAGE}

    cache:
      paths:
        - ~/.gradle/caches/modules-2/
        - ~/.gradle/wrapper/
